@echo off

where git >nul 2>nul
if %errorlevel% neq 0 (
    echo git not in PATH
    exit /B 0
)

where bindgen.exe >nul 2>nul
if %errorlevel% neq 0 (
    echo bindgen.exe not in PATH
    exit /B 0
)

git clone https://github.com/Immediate-Mode-UI/Nuklear nuklear
pushd nuklear
for /f %%i in ('git rev-parse HEAD') do set COMMIT_HASH=%%i
popd
(
echo # Bindings
echo.
echo Bindings generated by [odin-c-bindgen]^(https://github.com/karl-zylinski/odin-c-bindgen^)
echo.
echo Not all Nuklear features are included, this is the list of Nuklear flags used:
echo   * **NK_INCLUDE_FIXED_TYPES**
echo   * **NK_INCLUDE_STANDARD_BOOL**
echo   * **NK_INCLUDE_COMMAND_USERDATA**
echo   * **NK_KEYSTATE_BASED_INPUT**
echo.
echo Last Nuklear commit hash: [%COMMIT_HASH%]^(https://github.com/Immediate-Mode-UI/Nuklear/commit/%COMMIT_HASH%^)
echo.
) > README.md
type nuklear\Readme.md >> README.md
copy /Y nuklear\nuklear.h nuklear.h
rmdir /s /q nuklear

bindgen .

where cl >nul 2>nul
if %errorlevel% equ 0 (    
    cl /c /Z7 /DDEBUG nuklear.c
    lib /OUT:nuklear_windows_amd64_debug.lib nuklear.obj
    del nuklear.obj

    cl /c /O2 nuklear.c
    lib /OUT:nuklear_windows_amd64_release.lib nuklear.obj
    del nuklear.obj
)

where emcc >nul 2>nul
if %errorlevel% equ 0 (
    call emcc -c -g -DDEBUG nuklear.c -o nukler_wasm_debug.o
    call emcc -c -O2 nuklear.c -o nukler_wasm_release.o
)

:eof
